cannot make int k_seconds_per_day = 24*360 a const (I even stopped tryig doing that static)
libtool: link: x86_64-pc-linux-gnu-g++ -Wall -Wno-unused -Wno-deprecated-register -pipe -pipe -std=c++11 -g -O2 -O2 -Wl,-O1 -g
-o .libs/test-engine test_engine-test-engine.o utest-Account.o test_engine-utest-Budget.o test_engine-utest-Entry.o test_engine
-utest-Invoice.o test_engine-test-engine-kvp-properties.o test_engine-utest-gnc-pricedb.o dummy.o -pthread -Wl,--export-dynamic
 -pthread  ./.libs/libutest-Split.a -L/home/goujot/gentoo/usr/lib ./.libs/libutest-Trans.a /home/goujot/gentoo/var/tmp/portage/
app-office/gnucash-2.7.99999/work/gnucash-2.7.99999/src/test-core/.libs/libtest-core.so ../../../src/libqof/qof/.libs/libgnc-qo
f.so ../../../src/gnc-module/.libs/libgnc-module.so ../../../src/test-core/.libs/libtest-core.so ../.libs/libgncmod-engine.so .
./test-core/.libs/libgncmod-test-engine.a /home/goujot/gentoo/var/tmp/portage/app-office/gnucash-2.7.99999/work/gnucash-2.7.999
99/src/engine/.libs/libgncmod-engine.so /home/goujot/gentoo/var/tmp/portage/app-office/gnucash-2.7.99999/work/gnucash-2.7.99999
/src/gnc-module/.libs/libgnc-module.so /home/goujot/gentoo/var/tmp/portage/app-office/gnucash-2.7.99999/work/gnucash-2.7.99999/
src/core-utils/.libs/libgnc-core-utils.so ../../../src/core-utils/.libs/libgnc-core-utils.so /home/goujot/gentoo/usr/lib/libgui
le.so -lgmp -lcrypt /home/goujot/gentoo/usr/lib/libltdl.so -ldl /home/goujot/gentoo/var/tmp/portage/app-office/gnucash-2.7.9999
9/work/gnucash-2.7.99999/src/libqof/qof/.libs/libgnc-qof.so -lgio-2.0 -lgthread-2.0 -lgobject-2.0 -lgmodule-2.0 -lrt -lglib-2.0
 -lm -pthread -Wl,-rpath -Wl,/home/goujot/gentoo/usr/lib -Wl,-rpath -Wl,/home/goujot/gentoo/usr/lib/gnucash
../.libs/libgncmod-engine.so: undefined reference to `k_seconds_per_day'
collect2: error: ld returned 2 exit status
Makefile:1244: recipe for target 'test-engine' failed