forgot that my qof.h implies #include "gnc-date-p.h"
gnc-date.cpp:86:18: error: 'k_seconds_per_day' was declared 'extern' and later 'static' [-fpermissive]
 static const int k_seconds_per_day = 24*3600 ;
                  ^
In file included from qof.h:75:0,
                 from gnc-date.cpp:36:
gnc-date-p.h:38:18: error: previous declaration of 'k_seconds_per_day' [-fpermissive]
 extern const int k_seconds_per_day; // 24*3600
                  ^
gnc-date.cpp:89:12: error: 'k_show_time' was declared 'extern' and later 'static' [-fpermissive]
 static int k_show_time = 1 ; /* 1 if showing the time, 0 otherwise */
            ^
In file included from qof.h:75:0,
                 from gnc-date.cpp:36:
gnc-date-p.h:40:12: error: previous declaration of 'k_show_time' [-fpermissive]
 extern int k_show_time ; /* 1 if showing the time, 0 otherwise */
            ^
gnc-date.cpp:90:12: error: 'k_seconds_of_tolerance' was declared 'extern' and later 'static' [-fpermissive]
 static int k_seconds_of_tolerance = 3600 ; /* gnucash registers should be reopened at most k_seconds_of_tolerance after midnig
ht
            ^
In file included from qof.h:75:0,
                 from gnc-date.cpp:36:
gnc-date-p.h:41:12: error: previous declaration of 'k_seconds_of_tolerance' [-fpermissive]
 extern int k_seconds_of_tolerance; //3600 ? gnucash registers should be closed at most k_seconds_of_tolerance after midnight t