kvp_frame.cpp barks on static const int
../../../libtool  --tag=CXX   --mode=compile x86_64-pc-linux-gnu-g++ -DHAVE_CONFIG_H -I. -I../../.
.  -I../../../lib/libc -I../../../src -pthread -I/home/goujot/gentoo/usr/include/glib-2.0 -I/home/goujot/gentoo/usr/lib/glib-2.
0/include -I/usr/include -DG_LOG_DOMAIN=\"qof\"  -Wall -Wno-unused -Wno-deprecated-register -pipe  -pipe -std=c++11 -g  -O2 -O2
 -c -o kvp_frame.lo kvp_frame.cpp
In file included from qof.h:75:0,
                 from guid.cpp:57:
gnc-date-p.h:36:18: error: uninitialized const 'k_seconds_per_day' [-fpermissive]
 static const int k_seconds_per_day; // 24*3600